use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Deserialize)]
struct MapJson {
    version: u32,
    w: i32,
    h: i32,
    player_spawn: [i32; 2],
    tiles: Vec<String>,
    objects: Vec<MapObject>,
    mobs: Vec<MapMob>,
}

#[derive(Deserialize)]
struct MapObject {
    kind: String,
    tier: Option<i32>,
}

#[derive(Deserialize)]
struct MapMob {
    kind: String,
    x: i32,
    y: i32,
    hp: i32,
    attack: i32,
    strength: i32,
    defence: i32,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let map_path = manifest_dir.join("..").join("map.json");
    println!("cargo:rerun-if-changed={}", map_path.display());

    let raw = fs::read_to_string(&map_path)
        .unwrap_or_else(|err| panic!("read {}: {}", map_path.display(), err));
    let map: MapJson = serde_json::from_str(&raw)
        .unwrap_or_else(|err| panic!("parse {}: {}", map_path.display(), err));
    validate_map(&map);

    let generated = generate_map_rs(&map);
    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("generated_map.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("write {}: {}", out_path.display(), err));
}

fn validate_map(map: &MapJson) {
    if map.version != 1 {
        panic!("map.json version must be 1, got {}", map.version);
    }
    if map.w <= 0 || map.h <= 0 {
        panic!("map dimensions must be positive, got {}x{}", map.w, map.h);
    }
    let cell_count = (map.w as usize)
        .checked_mul(map.h as usize)
        .expect("map dimensions overflow usize");
    if map.tiles.len() != cell_count {
        panic!(
            "tiles length must be {}, got {}",
            cell_count,
            map.tiles.len()
        );
    }
    if map.objects.len() != cell_count {
        panic!(
            "objects length must be {}, got {}",
            cell_count,
            map.objects.len()
        );
    }

    for (i, tile) in map.tiles.iter().enumerate() {
        if tile_expr(tile).is_none() {
            panic!("unknown tile kind {:?} at cell {}", tile, i);
        }
    }
    for (i, object) in map.objects.iter().enumerate() {
        if object_expr(object).is_none() {
            panic!("invalid object {:?} at cell {}", object.kind, i);
        }
    }

    validate_open_cell(
        map,
        map.player_spawn[0],
        map.player_spawn[1],
        "player_spawn",
    );
    for (i, mob) in map.mobs.iter().enumerate() {
        if !matches!(
            mob.kind.as_str(),
            "goblin" | "club_goblin" | "ninja" | "dragon"
        ) {
            panic!("unknown mob kind {:?} at mobs[{}]", mob.kind, i);
        }
        if mob.hp <= 0 || mob.attack < 0 || mob.strength < 0 || mob.defence < 0 {
            panic!("invalid stats for mob {:?} at mobs[{}]", mob.kind, i);
        }
        validate_open_cell(map, mob.x, mob.y, &format!("mobs[{}]", i));
    }
}

fn validate_open_cell(map: &MapJson, x: i32, y: i32, label: &str) {
    if x < 0 || y < 0 || x >= map.w || y >= map.h {
        panic!("{} is out of bounds at {},{}", label, x, y);
    }
    let idx = (y * map.w + x) as usize;
    if map.tiles[idx] == "water" {
        panic!("{} is on water at {},{}", label, x, y);
    }
    if map.objects[idx].kind != "none" {
        panic!(
            "{} is blocked by object {:?} at {},{}",
            label, map.objects[idx].kind, x, y
        );
    }
}

fn generate_map_rs(map: &MapJson) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs from map.json\n");
    out.push_str("fn build_map() -> MapDef {\n");
    out.push_str("    MapDef {\n");
    out.push_str(&format!("        w: {},\n", map.w));
    out.push_str(&format!("        h: {},\n", map.h));
    out.push_str(&format!(
        "        player_spawn: ({}, {}),\n",
        map.player_spawn[0], map.player_spawn[1]
    ));

    out.push_str("        tiles: vec![\n");
    for row in map.tiles.chunks(map.w as usize) {
        out.push_str("            ");
        for tile in row {
            out.push_str(tile_expr(tile).expect("validated tile"));
            out.push_str(", ");
        }
        out.push('\n');
    }
    out.push_str("        ],\n");

    out.push_str("        objects: vec![\n");
    for row in map.objects.chunks(map.w as usize) {
        out.push_str("            ");
        for object in row {
            out.push_str(&object_expr(object).expect("validated object"));
            out.push_str(", ");
        }
        out.push('\n');
    }
    out.push_str("        ],\n");

    out.push_str("        mobs: vec![\n");
    for mob in &map.mobs {
        out.push_str(&format!(
            "            MobSpawn {{ kind: {:?}, x: {}, y: {}, hp: {}, attack: {}, strength: {}, defence: {} }},\n",
            mob.kind, mob.x, mob.y, mob.hp, mob.attack, mob.strength, mob.defence
        ));
    }
    out.push_str("        ],\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn tile_expr(tile: &str) -> Option<&'static str> {
    Some(match tile {
        "grass" => "Tile::Grass",
        "dirt" => "Tile::Dirt",
        "sand" => "Tile::Sand",
        "water" => "Tile::Water",
        "stone" => "Tile::Stone",
        "path" => "Tile::Path",
        _ => return None,
    })
}

fn object_expr(object: &MapObject) -> Option<String> {
    Some(match object.kind.as_str() {
        "none" => "Obj::None".into(),
        "tree" => {
            let tier = valid_tier(object.tier?)?;
            format!("Obj::Tree {{ tier: {tier}, hp: tree_def({tier}).hp }}")
        }
        "rock" => {
            let tier = valid_tier(object.tier?)?;
            format!("Obj::Rock {{ tier: {tier}, hp: rock_def({tier}).hp }}")
        }
        "bush" => "Obj::Bush { berries: 3, regrow: 0 }".into(),
        "boulder" => "Obj::Boulder".into(),
        "trader" => "Obj::Trader".into(),
        "angel" => "Obj::Angel".into(),
        _ => return None,
    })
}

fn valid_tier(tier: i32) -> Option<i32> {
    if (1..=4).contains(&tier) {
        Some(tier)
    } else {
        None
    }
}
